### ISSUE TITLE
demo saved in wrong folder

### ISSUE THREAD

**Issue by xSaqe** [shobhit-pathak/MatchZy#102]
My server hosting has demo auto upload from specific folder. I created the folder and updated MatchZy config so demos would be saved in it but they keep getting saved in MatchZy folder. I made sure that the name in the cfg file is the same as the folder name. Do i have to delete the MatchZy autocreated folder for it to work or is it just plugin error?

**Comment by shobhit-pathak** [comment]
Hey!

Could you please provide the exact command that you're using to change demo folder path? I'll try to re-create it on my end as well.

Thanks!
