### ISSUE TITLE
[BUG] Don't require .ready from spec players

### ISSUE THREAD

**Issue by GrzesiuS** [shobhit-pathak/MatchZy#104]
Hello,

We've discovered a bug here. When a player came from a team to Spec he needed to type .ready to start the match. I set 'required players to be ready" to 0 because sometimes we play 3v3, 4v4, and 5v5 so 0 is the best option for us but Spec players shouldn't be forced to be ready, they are just viewers.

**Comment by Max66888** [comment]
> 你好，
> 
> 我们在这里发现了一个错误。当一名球员从一个球队来到 Spec 时，他需要输入 .ready 来开始比赛。我将“要求玩家做好准备”设置为 0，因为有时我们会玩 3v3、4v4 和 5v5，所以 0 对我们来说是最好的选择，但不应该强迫 Spec 玩家做好准备，他们只是观众。

Yes, this is very common. In future versions, I would like to add the option to calculate Spec or not

**Comment by shobhit-pathak** [comment]
Hey!

Spec players can be admins as well, hence `matchzy_minimum_ready_required 0` requires all the connected players to be ready. You can anytime adjust `matchzy_minimum_ready_required` using RCON or use `.start` to force-start the match.

Thanks!
