### ISSUE TITLE
Use workshop maps

### ISSUE THREAD

**Issue by wundeer** [shobhit-pathak/MatchZy#107]
Is it possible to add a method to use workshop maps in the match settinga json file?

**Comment by shobhit-pathak** [comment]
Hey!

I haven't tried using workshop map with JSON config, but I think you can try providing the workshop map id in the config

Thanks!

**Comment by wundeer** [comment]
If we add add a map in the JSON like this: ws:workshopID we can use "ds_workshop_changelevel" and if we dont use "ws:" we can use "changeleven / map".

**Comment by shobhit-pathak** [comment]
Hey!

Since workshop map ids work with the json file, closing this issue.

Thanks!
