### ISSUE TITLE
Can't add bots

### ISSUE THREAD

**Issue by koikinov** [shobhit-pathak/MatchZy#110]
Sup mate,

 [MatchZy] Cannot add bots, the team is full! Use .nobots to remove the current bots.

I have tryed all settings and everything what i have found but nothing is working.

Can you help and tell me how i can remove those ghost bots.

**Comment by shobhit-pathak** [comment]
Hey!

Make sure that you do not have `nobots` in your server launch options, and also you've enough slots on the server for the bots to join in.

Thanks!

**Comment by koikinov** [comment]
Hi,

I have reset server like 10 times tryed different plugins and still it always say that same.

**Comment by shobhit-pathak** [comment]
Hey!

The issue is still non
