### ISSUE TITLE
[REQ] Remove support for some admin commands

### ISSUE THREAD

**Issue by crashzk** [shobhit-pathak/MatchZy#116]
I believe you can remove some admin commands from the plugin, namely:
- `.map <mapname>` - Changes the map
- `.asay <message>` - Say as an admin in all chat
- `.rcon <command>` - Sends command to the server

I believe that as we now have several plugins for administrative control, Admin System, Simple Admin and many others, we can leave these commands to them, as we can say that all servers have one of them installed.

**Comment by crashzk** [comment]
> Perhaps disabling as opposed to removing.
> 
> MatchZy having these commands make it's extremely easy for tournaments and LANS, removing these would just add unnecessary overhead for people using it for these kinds of things.

Indeed, an option to disable these features would be interesting.

However, I also don't see the need, using your example, in all cases we always have a user with RCON access, and having this can perform all these functions using RCON from CS2 itself.

Exchange maps, chat messages, and much more.

In any case, an option to disable just these features instead of removing them would really be more interesting.

**Comment by sphaxa** [comment]
Well, for Fragadelphia we have limited rcon but for live admins they usually log in directly in spectator. 

Just saying it makes sense to have them for single installs. And less confusing with needing to to CS2 commands and or installing another plugin.

**Comment by shobhit-pathak** [comment]
Hey!

As @sphaxa had mentioned, these commands are helpful in tournaments and when you do not want to have multiple plugins in the server.
If these commands do not cause any issues, I think we can continue without disabling them as well.
