### ISSUE TITLE
[BUG] Demo Recording Bug

### ISSUE THREAD

**Issue by Sh1su** [shobhit-pathak/MatchZy#118]
Hello Shobhit,

One of our players has reported to me that demo recording is not functioning correctly. The demo either cannot be recorded at all or is very buggy.

Upon analyzing the issues, I have also observed the mentioned errors. The following error messages seem to be relevant:

```shell
demo file version 'valve_demo_2' engine version 'valve_demo_2' on file
```

In the buggy demo, it starts before the beginning of the first round and continues for as long as the demo has been recorded. We did not encounter these issues with default demo recording. Could you please try to reproduce the error on your end?

I have uploaded the demo for testing purposes: https://file.io/MOrS9fxNX2V3

Kind regards,
Marcel K.
Technical Support at OCB

**Comment by shobhit-pathak** [comment]
Hey!

Apologies for replying very late.
We use the default commands to record the demo, and I've tried multiple demos on my side which seems to be working fine.

Can you confirm if you're still facing this issue with the latest updates?

Thanks!
