### ISSUE TITLE
Ability to take admin via !admin command

### ISSUE THREAD

**Issue by aronmgv** [shobhit-pathak/MatchZy#133]
I don't really want to specify admins for the server.. It would make sense that first player joining the server would take admin rights via command and only this player will be admin until he either uses `!admin` command again or disconnects from the server..

**Comment by shobhit-pathak** [comment]
Hey!

There is a convar `matchzy_everyone_is_admin`, you set it to `true` and everyone will get the admin powers.

Having a command to take the admin rights will have many downsides and issues.

Thanks!
