### ISSUE TITLE
Round restart delay in match mode

### ISSUE THREAD

**Issue by weeestar** [shobhit-pathak/MatchZy#135]
In live.cfg, the parameter mp_round_restart_delay is set to 5.

But we noticed that when match is running, it appears to be shorter than 5 seconds. We don't have time to get guns after defusing the bomb or killing the last enemy player. In knife.cfg, it's set to 3 but in server, the round restarts immediately.

I've searched for additional parameter but I can't find anything. Also, didn't see this issue reported in your repository.

**Comment by shobhit-pathak** [comment]
Hey!

In Knife round it is restarted immediately, but for the live match, it should be same as the `mp_round_restart_delay` set in the live.cfg as the plugin doesn't interfere with that.

Thanks!
