### ISSUE TITLE
When switching teams, players produce the same color.

### ISSUE THREAD

**Issue by kureCC** [shobhit-pathak/MatchZy#136]
When switching teams, players produce the same color.

**Comment by shobhit-pathak** [comment]
Hey!

This issue does not seem related to the plugin, rather this could be a game bug.
You can try the steps below:
![431478953_944929130549974_3271554168715468661_n](https://github.com/shobhit-pathak/MatchZy/assets/140690706/7b569bee-e737-468c-b8c4-954b7b909d04)
