### ISSUE TITLE
Can't disable mp_overtime_enable, because plugin enables it when match goes live

### ISSUE THREAD

**Issue by borzaka** [shobhit-pathak/MatchZy#137]
During group stage matches, it's very common that matches can end up tie, and won't go to overtime. But the plugin enables overtime, no matter what. Disable it in the `live.cfg` won't help, because this code is executed after the `live.cfg`:

https://github.com/shobhit-pathak/MatchZy/blob/6042de1d1f425a4620c1283d9ec9283ab3e6cf05/Utility.cs#L255

Possible solutions:
- remove the above mentioned line from the code ([PugSetup does the same](https://github.com/splewis/csgo-pug-setup/blob/fac5f982e96c26913aa5134d7ab9c0e74a686482/scripting/pugsetup.sp#L1941))
- add a new `.cfg` file to execute after the above code

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for pointing it out and apologies for missing it, silly of me.
I'll fix this in the next update, I should probably read its value from the live.cfg rather than hardcoding it like this.

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

This is now fixed with the 0.7.11 release.

Thanks!

**Comment by borzaka** [comment]
Thank you!

One question:
What happens when I have multiple `mp_overtime_enable` setting in my `live.cfg`?
I like to keep the original `live.cfg` untouched, and put my custom variables at the bottom.

`live.cfg`
```
...
mp_overtime_enable 1
...

// My custom variables
mp_overtime_enable 0
```

**Comment by borzaka** [comment]
Well, I just tested, and its finds the first occurrence. So my custom cvars on the bottom of the file gets ignored.

**Comment by shobhit-pathak** [comment]
Hey!

I get the problem here, it should read the last occurrence. But it still will have problem if someone is overriding it using some other cfg. We would have to think of a better solution here

**Comment by borzaka** [comment]
The live.cfg and live_override.cfg should be the last executed before the match goes live. Every live cvars should be set inside those two files. I won't and no one should disable overtime in server.cfg, or in gamemode_competitive_server.cfg.
