### ISSUE TITLE
Upload demos 

### ISSUE THREAD

**Issue by onefraks** [shobhit-pathak/MatchZy#139]
I have seen the command of matchzy_demo_upload_url "https://your-website.com/upload-endpoint" and I have read the documentation but I don't know which websites I can use to upload automatically, which url would you recommend?

Thank you and wonderful congratulations for your plugin.

**Comment by shobhit-pathak** [comment]
Hey!

You'll probably have to host your own website/endpoint which can handle these demo uploads, or you can simply use the G5V/G5API setup.

Thanks!
