### ISSUE TITLE
Pls when the player locks in the team is finished, I write it like this and they don't know why it's always a mess to take effect 

### ISSUE THREAD

**Issue by akayedi** [shobhit-pathak/MatchZy#14]
RegisterEventHandler<EventPlayerTeam>((@event, info) =>
            {
                string currentDirectory = Directory.GetCurrentDirectory();
                int UID = (int)@event.Userid.UserId;
                int team = (int)@event.Team;
                var team3Players = team1Players;
                var team4Players = team2Players;
                if (Number_rounds == 13 || Number_rounds == 26 || (Number_rounds > 26 && Number_rounds % 6 == 0))
                {
                    team3Players = team1Players;
                    team4Players = team2Players;
                }else{ team3Players = team2Players;team4Players = team1Players;}
                int t = 0;
                if (team3Players.TryGetProperty(@event.Userid.SteamID.ToString(), out _))
                {
                    t = 3;
                }
                else if (team4Players.TryGetProperty(@event.Userid.SteamID.ToString(), out _))
                {
                    t = 2;
                }

                _PlayerController = Utilities.GetPlayerFromUserid(UID);
                Server.NextFrame(() =>
                {
                    if (t != 0 && team != t)
                    {
                        _PlayerController.SwitchTeam((CounterStrikeSharp.API.Modules.Utils.CsTeam)(int)t);
                        _PlayerController.PlayerPawn.Value.CommitSuicide(true, true);
                    }
                    else
                    {
                        if (t == 0)
                        {
                            t = 1;
                            _PlayerController.SwitchTeam((CounterStrikeSharp.API.Modules.Utils.CsTeam)(int)t);
                            _PlayerController.PlayerPawn.Value.CommitSuicide(true, true);
                        }

                    }
                    Log($"T= {t}");
                });

                return HookResult.Continue;
            });

**Comment by shobhit-pathak** [comment]
Hey, could you please help me understand what are you exactly trying to achieve here?

**Comment by akayedi** [comment]
> 嘿，你能帮我理解你到底想在这里实现什么吗？

I'm trying to lock down the team members here, and when they try to switch sides, I'll judge the team I've read, and if it's not the designated team, I'll make them kill themselves and go back to the team they deserve

**Comment by akayedi** [comment]
I'm going to read this json file and lock the player team on my code above, but my previous work is normal, and when it comes to switching sides, I get wrong, can you help me?

There is a possibility that he will kill a correct player, and there is also a possibility that the player will be forced to switch to the wrong team when switching sides, which I suspect may be logically problematic for me

> Hey, could you please help me understand what are you exactly trying to achieve here?

**Comment by crashzk** [comment]
From what I understand, the problem would be the limit of players on the right team?

We need some blocking on the teams so that when there are 5 players on each team, the SPECS cannot enter the teams and neither can the players on the teams change teams.

In simple terms, Lock Team to block team changes during the competition.

**Comment by shobhit-pathak** [comment]
Yes I had a word with him regarding this, and the locking teams using JSON will be coming soon to MatchZy ;)
