### ISSUE TITLE
BUG Report Server restart when saving demo

### ISSUE THREAD

**Issue by Sh1su** [shobhit-pathak/MatchZy#147]
Hello shobhit pathak

Since version 0.7.0 we have had the problem that our server keeps crashing when writing the demo. Due to the missing logs, I can't narrow down the error any further. Is it possible that your plugin can cause such a problem?

Best regards
Sh1su

**Comment by mrc4tt** [comment]
It's good idea to tell us which CSS version you're on. ^

**Comment by shobhit-pathak** [comment]
Hey!

We have a lot of servers running up and never faced such issue.
Would it be possible to get the logs so that we can debug it further?

You can also try the latest Matchzy with cssharp release, just to be sure.

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

Sure, it would be better to update the plugin and CSS and then test.
