### ISSUE TITLE
Make .spawn use competitive only spawns

### ISSUE THREAD

**Issue by ar1a** [shobhit-pathak/MatchZy#15]
Hi, trying to run inferno spawn smokes, i expect .spawn to go through 1-6 but when using those spawns, it spawns me in casual/(esea pistol) round spawns. 

I know mm-cs2-scrim has this sorted in this function, maybe that could help 
https://github.com/marqdevx/mm-cs2-scrim/blob/7a0ab08ba3fffff4379de318567b7222b68377e7/src/commands.cpp#L183

**Comment by shobhit-pathak** [comment]
Hey, thanks for pointing this out!
I'll fix this in the next update! :D

**Comment by shobhit-pathak** [comment]
Hey!
This has been added in the latest release, thanks!
https://github.com/shobhit-pathak/MatchZy/releases/
