### ISSUE TITLE
After running css_start, the live.cfg file is reported as loaded, but the commands are not updated.

### ISSUE THREAD

**Issue by gen0ka** [shobhit-pathak/MatchZy#154]
At the beginning of the game after the knife round, the **live.cfg** file is loaded according to the console, but the commands present in the configuration file are not updated.

Commands like **mp_overtime_enable** and **mp_match_can_clinch** are disabled after the start of the match.

Can you help me?

**Comment by shobhit-pathak** [comment]
Hey!

There was an issue with `mp_overtime_enable` and `mp_match_can_clinch` commands which were getting overridden by playout settings.

This issue should be fixed with the 0.7.11 release, requesting you to please check it now.

Thanks!

**Comment by gen0ka** [comment]
![image](https://github.com/shobhit-pathak/MatchZy/assets/123119893/f22aa208-1cc0-45a7-8bc1-e9ff1b438789)


Even after I force the start of the game it does not consider the values in live.cfg, this file is still at default values, it has not been modified.

**Comment by gen0ka** [comment]
Thanks for the answer.

I incorrectly modified config.cfg and enabled playout by default, disabling the options I mentioned. I turned playout back to off by default and everything went fine.
