### ISSUE TITLE
[Feature] .bestspawn/.worstspawn

### ISSUE THREAD

**Issue by mavproductions** [shobhit-pathak/MatchZy#156]
Hey @shobhit-pathak !

Wondering if you could support `.bestspawn`/`.worstspawn` command with prac-mode. Basically just giving use a quick alias to use the best or worst spawn of the current team selected at the current position of the player.

Thanks for considering 🙂

**Comment by shobhit-pathak** [comment]
Hey!

This has been added in the 0.7.10 release of MatchZy

Thanks!

**Comment by mavproductions** [comment]
TY @shobhit-pathak !!
