### ISSUE TITLE
slow server frame

### ISSUE THREAD

**Issue by doctoralpha** [shobhit-pathak/MatchZy#159]
hi
i run server on windows server 2022 with 12gb ram and 6 cores cpu.
everything is ok before running match mode!
when i run the match i get slow server frame, same players in warmup or prac mode have no problem but when match start all players get slow server frame and server get lag.

**Comment by Rafex788** [comment]
yeah i have same issue

**Comment by danir-de** [comment]
Having the same issue since CS2 updates in February 2024. I don't think this is related to MatchZy.

**Comment by shobhit-pathak** [comment]
Hey!

We have multiple servers running but do not face lag/slow server frame issue. As @danir-de, it might be due to CS2 updates.
If you're using a MySQL database connection, make sure there is no lag or issue from the DB side.

Thanks!
