### ISSUE TITLE
[Fix] .help menus seem to be behind on updates

### ISSUE THREAD

**Issue by mavproductions** [shobhit-pathak/MatchZy#161]
Hey @shobhit-pathak!!

I'm just wondering. Is there any chance the matchzy `.help` menu could get a revamp? I have a few users that rely on these types of menus and it seems to be behind on a few updates. 

It's nice that it dynamically shows the help according to what `matchzy_autostart_mode` is enabled, but it looks like both modes could use some extra info added perhaps. I feel like if you removed the chat prefix for these commands, it might provide extra real-estate for help info outputted as well. Or at least removed the prefix after the first line and just concatenated `\u2029` to deal with multi-line ingame documentation.

Thank you for considering this! 😀😀🙂🙂

**Comment by shobhit-pathak** [comment]
Hey!

We've improved the help message in 0.7.11 release.
![20240519232605_1](https://github.com/shobhit-pathak/MatchZy/assets/140690706/53cce33c-a9fc-4246-8bf2-d6e9b3813d34)


Thanks!
