### ISSUE TITLE
JSON: Make Match ID string

### ISSUE THREAD

**Issue by FlowingSPDG** [shobhit-pathak/MatchZy#164]
context: https://github.com/splewis/get5/issues/940

Originally get5 was also using int as match ID, but I requested to make it string for API purposes so it became string.

Currently MatchZy is also using int as match ID but as same reason I'd like to use string for our current projects like https://github.com/FlowingSPDG/Got5 .

I'll create PR if I can

**Comment by shobhit-pathak** [comment]
Hey!

Changing `matchid` to string in MatchZy will have a lot of problems, as `matchid` as specified as auto-increment integer in all the db table schemas.
The reason behind `matchid` being integer is that when a normal pug/scrim game started (without get5 set-up), the server will still create an integer matchid and use that to store all the stats in the database.

**Comment by FlowingSPDG** [comment]
Hi @shobhit-pathak !
Oh I see. I personally do not have any issue with integer MatchID, so I suggest that we'll continue using Integer and update documents and add migration/difference documents for get5?

**Comment by FlowingSPDG** [comment]
Maybe its good idea to make matchID int on Webhook instead?
https://shobhit-pathak.github.io/MatchZy/events.html#tag/Series-Flow/paths/MatchZyOnSeriesInit/post

**Comment by shobhit-pathak** [comment]
Hey @FlowingSPDG,

Yeah it should be int there, thanks for pointing it out. I'll fix it!

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for the contribution. Closing this issue since we've changed it to int completely
