### ISSUE TITLE
Getting error on CS2 docker image

### ISSUE THREAD

**Issue by soren33322** [shobhit-pathak/MatchZy#165]
What should I do?

It somehow now don't want to start. I have tried 7.11 and 7.10.
![image](https://github.com/shobhit-pathak/MatchZy/assets/42936505/8ae229cd-a6da-400b-9c85-da7db77485a5)

Hope someone know how to fix

**Comment by crashzk** [comment]
Update CSSharp: https://github.com/roflmuffin/CounterStrikeSharp/releases/latest

**Comment by shobhit-pathak** [comment]
Hey!
As crash had mentioned, update CSSharp or use MatchZy with CSSharp release.
Thanks!
