### ISSUE TITLE
[BUG] Broken saved nades position.

### ISSUE THREAD

**Issue by sequ3r** [shobhit-pathak/MatchZy#170]
I have a bug, using the latest version. When you're going to load the saved nade, the saved position isn't accurate. When you loaded grenade you're stuck and the position isn't accurate, you need to move a little bit to unstuck. It's annoying, please fix that.

**Comment by shobhit-pathak** [comment]
Hey!
The stuck issue is now resolved with 0.8.2 update, thanks!
