### ISSUE TITLE
TV Source or GOTV

### ISSUE THREAD

**Issue by Geant200** [shobhit-pathak/MatchZy#177]
Good morning,

I don't really understand how to activate the TV Source or GOTV and recover the video files of the match?

G5API is compatible for Windows server?.

Can you tell me more, thank you in advance.

**Comment by shobhit-pathak** [comment]
Hey!
You just need `tv_enable` in your `server.cfg`, and MatchZy will automatically record the demos for you and save it in `csgo/MatchZy` folder. You can also configure the demos save path using `matchzy_demo_path`.

G5API/G5V should be compatible with Windows, you can use the docker image for that.

Let me know if you have further doubts, you can also join MatchZy's discord.
