### ISSUE TITLE
Server crashing on team select

### ISSUE THREAD

**Issue by L1teD** [shobhit-pathak/MatchZy#178]
Server crashing on team select

`css_plugins list`
```
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADED]: "MatchZy" (0.7.12) by WD- (https://github.com/shobhit-pathak/)
    A plugin for running and managing CS2 practice/pugs/scrims/matches!
```

**Comment by shobhit-pathak** [comment]
Hey!

Please make sure that you do not have any command like `sv_coaching_enabled` in any of your cfg (warmup, live, knife, gamemode_competitive, etc)
Once you remove that and other unused commands from cfg, it should be fixed.

**Comment by L1teD** [comment]
> Hey!
> 
> Please make sure that you do not have any command like `sv_coaching_enabled` in any of your cfg (warmup, live, knife, gamemode_competitive, etc) Once you remove that and other unused commands from cfg, it should be fixed.

I looked inside every cfg i have, and everywhere `sv_coaching_enabled` was set to `false`

**Comment by L1teD** [comment]
nvm, i didn't noticed in a couple .cfg files this command and that was the issue
i deleted it from all files i could find and everything works now

thanks for help!
