### ISSUE TITLE
mp_round_restart_delay to be 7?

### ISSUE THREAD

**Issue by FlowingSPDG** [shobhit-pathak/MatchZy#183]
Hi again,

I was running small tournament this Saturday and players reported ``mp_round_restart_delay`` is shorter than competitive.
In CS:GO, I remember ESL was using it shorter(like 3seconds?) but I do not know about competitive settings in CS2.

At least I can tell wingman is using different delay than competitive:
https://github.com/shobhit-pathak/MatchZy/blob/9cee426c2065566b3425843edce25ec24f2231e0/Utility.cs#L1143-L1149

**Comment by rpkaul** [comment]
casual 10 seconds
MM/Pugs 7 seconds
Official tournament/scrim 5 seconds.
but recently i saw faceit is also using 7 seconds for some reason before it was 5 seconds for all official matches.

**Comment by FlowingSPDG** [comment]
Interesting... since there's no "official" competitive config so I guess MatchZy can use 7as well?

**Comment by rpkaul** [comment]
https://x.com/rusty_csgo/status/1500606384290865156?s=46
https://x.com/elige/status/1397055731032068098?s=46

Based on these tweets, it looks like Faceit has been using 7 seconds for a long time. However, it should be 5 seconds for official matches. Also, it depends on the Tournament Organisers, and you can change the value in live.cfg."

**Comment by FlowingSPDG** [comment]
Thanks for sharing their tweets man!
You're right... I'm worrying about that live.cfg will be updated when I update MatchZy since it overwrites live.cfg too.

I'll open PR for adding "exec live_override.cfg" at end of the live.cfg file just like gamemode_competitive so TOs can customize variables.

**Comment by borzaka** [comment]
+1 vote for `mp_round_restart_delay 5` for `live.cfg`.

**Comment by shobhit-pathak** [comment]
Hey guys!

Am I missing something here or can this issue be closed? :P
