### ISSUE TITLE
Disable damage reporting in chat

### ISSUE THREAD

**Issue by Smithyplays** [shobhit-pathak/MatchZy#186]
While using the plugin, I noticed that there is no way to disable damage reporting in chat. (At least not that I know of).
This was possible in Get5 CS:GO with the parameter "get5_print_damage = 0" set in the config file.
Would love to see this option in MatchZy.

**Comment by shobhit-pathak** [comment]
Hey!
Thanks for the suggestion, I will pick this up soon

**Comment by shobhit-pathak** [comment]
Hey!

`matchzy_enable_damage_report` convar has been added in the 0.8.1 update to toggle damage reporting in the chat.

Thanks!
