### ISSUE TITLE
cash_team_planted_bomb_but_defused should be 600, not 800

### ISSUE THREAD

**Issue by borzaka** [shobhit-pathak/MatchZy#188]
They changed the economy in Release Notes for 5/23/2024: https://store.steampowered.com/news/app/730/view/4177730135016140040

> Reduced the terrorist team award when bomb was planted but defused from $800 to $600, to decrease the impact of the first-round on subsequent rounds

The console command for this variable is: `cash_team_planted_bomb_but_defused`

`gamemode_competitive.cfg` and `gamemode_competitive2v2.cfg` has this setting:
`cash_team_planted_bomb_but_defused 600`

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for highlighting, I'll do the required changes!

**Comment by shobhit-pathak** [comment]
Hey!

Fixed in the 0.7.13 update, thanks!
