### ISSUE TITLE
CounterStrikeSharp is now available for Windows

### ISSUE THREAD

**Issue by ChocOranger** [shobhit-pathak/MatchZy#19]
Just a heads up that CounterStrikeSharp is available for windows.
https://github.com/roflmuffin/CounterStrikeSharp/releases

Readme says CSSharp is only for Linux and releases should have a windows version.

**Comment by shobhit-pathak** [comment]
Hey, thanks!
I'll once test MatchZy on windows, and then update the releases/readme accordingly! :D

**Comment by shobhit-pathak** [comment]
Hey!

I've tested MatchZy on windows and it seems to be working fine
Hence I've updated the readme as well

Thanks! :D
