### ISSUE TITLE
Server crashing after live.cfg is ran by the server

### ISSUE THREAD

**Issue by nrbcs** [shobhit-pathak/MatchZy#193]
Within this week it seems that my team's dathost server using matchzy only crashed while trying to start a match/scrim, using the live.cfg file. I have isolated the issue to this file as the server operates normally otherwise, and so does the plugin for that matter, .prac, and all other commands work flawlessly, only when trying to start a match/scrim with another team. Also happens when I force start it alone in the server.

EDIT: I've also tried disabling gotv and the crashing persists

**Comment by meechu57** [comment]
I've had this same issue. I just did a fresh install of Metamod v1293 and CounterStrikeSharp v247. This issue started before the latest MatchZy release, so I'm unsure where the hitch is coming from.

**Comment by nrbcs** [comment]
> I've had this same issue. I just did a fresh install of Metamod v1293 and CounterStrikeSharp v247. This issue started before the latest MatchZy release, so I'm unsure where the hitch is coming from. I've also disabled GOTV.

Dathost isn't updating the plugin automatically, it still shows the previous version from 15 days ago. Manually update the plugin with the most recent release from 5 days ago and it works flawlessly again, not sure why out of nowhere dathost cannot auto update the plugin, but this worked for me.
