### ISSUE TITLE
Scrim with coaches bomb glitch

### ISSUE THREAD

**Issue by xGuysOG** [shobhit-pathak/MatchZy#194]
It seems if you have a coach the bomb can glitch, so 1 player has a bomb, but because the coach might have spawned with the bomb or smth like it, it also looks like there is a bomb in spawn, its very problematic

**Comment by nrbcs** [comment]
Also have had this issue for closer to 2 months when we have our coach in the coaching slot, within this week we aren't even able to scrim anybody, our server just crashes after starting the scrim.

**Comment by shobhit-pathak** [comment]
Hey!

Would it be possible for you to share a clip or screenshot of the same?
The coach seems to be very problematic 😅

**Comment by shobhit-pathak** [comment]
Hey @xGuysOG @nrbcs,

We have made some improvements in the coaching system (0.8.2 update) and these glitches should also be resolved with it.
Requesting you to take a look at it!
