### ISSUE TITLE
Server crashes after knife round (when the match will start)

### ISSUE THREAD

**Issue by gabrielcorradinis** [shobhit-pathak/MatchZy#195]
When the knife round ends, we start the game, then the server crashes and I don't find any errors in the console logs. 

> GOTV is disabled. 
> VAC is enabled. 

Do we have a solution for this without updating the plugin or is it necessary to adjust the code?

**Comment by nrbcs** [comment]
If your using dathost or just on an old version of the plugin this will happen. I noticed my dathost server was running a previous version which caused the crashes everytime the match would start, try updating to the most recent version, should fix your issue!

**Comment by nrbcs** [comment]
> > If your using dathost or just on an old version of the plugin this will happen. I noticed my dathost server was running a previous version which caused the crashes everytime the match would start, try updating to the most recent version, should fix your issue!
> 
> I'm using DatHost, yes, the panel shows that it was Updated today

You probably have already, but try rebooting the server so the plugin update takes place. Or just remove the plugin entirely, save and reboot, and then reinstall it again through the plugin tab on dathost, then save and reboot again. I'm having no issues atm with my dathost server on the current version, maybe another plugin is creating the hitch?

**Comment by shobhit-pathak** [comment]
Hey!

Can you try with the latest MatchZy update (0.8.1) and latest CS#? You should not encounter any crashes.

**Comment by shobhit-pathak** [comment]
Hey guys!
Some people have confirmed that it does not crash anymore after the knife round, closing this issue now.

Thanks!
