### ISSUE TITLE
More detailed error messages

### ISSUE THREAD

**Issue by Porcellacion** [shobhit-pathak/MatchZy#2]
If I'm not admin on the server, and try to type: !scrim or !prac, it doesn't say anything at all.

It would be good if it said something like "You must be admin in order to...."

**Comment by shobhit-pathak** [comment]
Hey!
Thanks for the suggestion, having a message like this would be great!
I'll definitely pick this up in the next update :D

**Comment by shobhit-pathak** [comment]
Hey!

I've added this in `0.3.0-alpha` release of MatchZy!
If a non-admin player uses admin commands, they'll get the message: 
`You must be admin in order to use this command!`
