### ISSUE TITLE
Regression: switching maps after veto makes matchStarted=true

### ISSUE THREAD

**Issue by milkywayfarer** [shobhit-pathak/MatchZy#217]
Caught on 0.8.3 yesterday. This was not the case on update 0.8.1, so I consider it a regression.

Upon completing the veto and changing the map, we go to a warmup where every player should ready up, but plugin decides that `matchStarted==true` and stops waiting for players to ready up, stops chat messaging and ignores `.ready`, making match unstartable. Pausing or stopping does not work and leaves the warmup state active.

Without the veto everything is ok.

Seems like it might be an auto-side-selection trouble, if selecting a side makes the player ready.

**Comment by milkywayfarer** [comment]
Log looks like this: `[MatchZy] [!ready command] Sent by: 1 readyAvailable: True matchStarted: True`

I believe these two variables should always be the opposite of each other :D

**Comment by shobhit-pathak** [comment]
Hey @milkywayfarer,

Thanks for the observations and letting me know, helps a lot! I had added `Utility.cs:696 (`matchStarted = true`)` in the newer update because the flag was not getting initialised on knife round, but I think thats the wrong place to do it since it messes up with the veto.
I'll put it in the knife round function and test it.

**Comment by shobhit-pathak** [comment]
Hey @milkywayfarer,

I've pushed an update which should fix it, can you try with the 0.8.4 version?

**Comment by milkywayfarer** [comment]
Hey thanks for the update, we will get that tested tomorrow on 2 servers

**Comment by milkywayfarer** [comment]
Hey @shobhit-pathak,

We tested the latest version (0.8.5) on 3 servers and everything went as expected, aside some instances where creating a wingman match does not make the gamemode wingman, but it's not related.

Thanks!
