### ISSUE TITLE
Matchzy Text Message's Color Issue

### ISSUE THREAD

**Issue by smpcheathunt** [shobhit-pathak/MatchZy#240]
In the eng lang folder, I changed the text colors to {SILVER} which I preferred. Even behind and after the natives such as {0}, but in-game the natives are still in green color.  Also, where to change the damage report colors?

Example:
Numbers of Players Required: 1 (The 1 here would be green colored)

Expected Behaviour:
Numbers of Players Required: 1 (Which all the text are all silver colored)

**Comment by smpcheathunt** [comment]
Also, I'm sorry but the LIVE text message color, how do we change them?

**Comment by mrc4tt** [comment]
> Also, I'm sorry but the LIVE text message color, how do we change them?

You need to modify the plugin and re-compile it.

**Comment by smpcheathunt** [comment]
how do you compile them? if i may ask?

**Comment by shobhit-pathak** [comment]
Hi,

Please refer to the doc for compiling the plugin: https://shobhit-pathak.github.io/MatchZy/developers/

Thanks!
