### ISSUE TITLE
[Suggestion] Add toggle to allow playing all 24-rounds game for Scrims

### ISSUE THREAD

**Issue by execut1ve** [shobhit-pathak/MatchZy#26]
You can set it up with the following command.

`mp_match_can_clinch <true/false>`

The default is true; setting it to false will play a 24rounds game.
I wish this could be used in the chat command.

**Comment by shobhit-pathak** [comment]
Hey!
You can use `!rcon mp_match_can_clinch false` in chat to set it to false via chat!
Though, I'll add a toggle setting for the same :D

**Comment by execut1ve** [comment]
OK, I did not know that I could use the command `!rcon` because I did not see anywhere that the command was.
However, it is very good to have a dedicated command available.

Thank you very much :)

**Comment by shobhit-pathak** [comment]
Thanks for pointing it out, it seems I've missed the !rcon command in readme. I'll add it there :D
Also, having a dedicated command would be great, so I'll get it done soon, but till then you can use !rcon to send commands :D

**Comment by shobhit-pathak** [comment]
Hey!

This has been added in MatchZy 0.4.3 update, now we have `.playout` command using which you can enable playout of all rounds (for scrims)

Thanks!
