### ISSUE TITLE
[Suggestion] Rethrow last grenade .rethrow

### ISSUE THREAD

**Issue by andre-luca** [shobhit-pathak/MatchZy#27]
Hey, 

I really like this plugin. It has almost all features I wish for a practice Server. One thing I wish if it is possible would be to add a command to rethrow the last grenade like the sv_rethrow_last_grenade command in console. Maybe something like .rethrow.

And I have a little question is it possible to get damage info alongside the flashed time info?

Keep up the good work.

**Comment by shobhit-pathak** [comment]
Hey!
`sv_rethrow_last_grenade` throws the last thrown grenade on the server, but `.rethrow` should be player specific.
I've started exploring the `.rethrow` command and hopefully it can be implemented soon :D

Till then, you can use `sv_rethrow_last_grenade` like this:
`!rcon sv_rethrow_last_grenade` (In chat. You can also bind it to some button)

**Comment by andre-luca** [comment]
Hey thanks for the reply :) The rcon command is a nice solution thanks!

For the grenade damage it would be super helpfull to get damage info everytime I deal damage on a bot in prac mode. That would help me to find the best lineups for he's for example.

**Comment by Tuytinger** [comment]
Hey,

I found this old post and would like to ask if it is possible to add the mentioned feature. The .rcon command does work but somehow it doesn't work when bound to a key. No idea why it doesn't work though since it says "command sent succesfully" when using this bind: .rcon "say sv_rethrow_last_grenade". Can you help me somehow or add the command? Hoping that the say bind works for that though ^^

**Comment by shobhit-pathak** [comment]
Hey @Tuytinger!

Apologies for the late reply.
To bind it to a key, you can do it like this:
`bind o css_rcon sv_rethrow_last_grenade`

You can replace o with the key of your choice, and it will work as expected
And we're also working on a player specific rethrow, hopefully that can be done ASAP

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

`!rethrow` command has been added in the latest v0.7.0 release of MatchZy, alongside many improvement in practice mode.

Thanks!
