### ISSUE TITLE
[REQ] Add a force un/pause for admins and allow admins to unpause as a player

### ISSUE THREAD

**Issue by ChocOranger** [shobhit-pathak/MatchZy#28]
Add admin commands .forcepause (or .adminpause) and .forceunpause (or .adminunpause)

Admins currently have .pause and .unpause but these force the pause and unpause.
For admins, .pause and .unpause should work the same as for non-admins.

The problem is that if admins are playing in the match they have no way of unpausing and the match waiting for the other team to unpause. It will simply unpause the game and continue. Not a good experience for the other team.

**Comment by shobhit-pathak** [comment]
Hey!

- Added `.forcepause` and `.forceunpause` commands for admins so that they can use `.pause` and `.unpause` as a player while playing (Use `.fp` and `.fup` for shorter commands)

This has been added in 0.4.3-alpha release of MatchZy

Thanks! :D
