### ISSUE TITLE
how to disable competitive mode 

### ISSUE THREAD

**Issue by kifstton** [shobhit-pathak/MatchZy#3]
how to disable competitive mode and constant spam in chat messages "ready"

**Comment by shobhit-pathak** [comment]
Hey, the only way to switch from competitive mode is using `.prac` to switch to the practice mode.

Could you please help me with understand why do we need to disable it?

Because ready/unready functionality is needed for matches hence we display those messages in warmup

**Comment by kifstton** [comment]
I don’t use this mode, so I don’t need it, and the constant messages in the chat so that I send “ready” to the chat.
Alternatively, you can simply add a command to permanently disable the competitive mod or so that you can disable it in the config.

**Comment by shobhit-pathak** [comment]
Understood, but what should be the default mode when competitive mode will be disabled?
Simply warmup?

**Comment by kifstton** [comment]
Yes, you can warmup, but it would be even better, for example, to enable the prac mode by default.

**Comment by kifstton** [comment]
and already from the practical mod it was possible to activate the match mode

**Comment by shobhit-pathak** [comment]
Yes, vice versa. From competitive mode also, practice mode can be started by typing `.prac`. That would disable the chat messages as well.
I'll check on adding the default mod in the config file, thanks!

**Comment by shobhit-pathak** [comment]
You can load/unload or stop/start MatchZy plugin using `css_plugins` command.
Usage:
`css_plugins stop/start/restart/load/unload/reload <pluginname>`

So you can have `css_plugins stop "MatchZy"` command in your cfg where you'll start retake mode to deactivate MatchZy
And when you want to enter match mode, you can use `css_plugins start "MatchZy"`, that will re-activate MatchZy

If start/stop doesn't work, you can try load/unload as well.
Note: This will disable the plugin completely, we cannot disable it partially.
