### ISSUE TITLE
[REQ] Web/FTP demo upload system

### ISSUE THREAD

**Issue by crashzk** [shobhit-pathak/MatchZy#32]
I believe the feature of sending the demo to the web/ftp after the competition has ended would be interesting.

So I could provide a link for players to download. And why not improve even further and offer support for discord, with a webhook sending system to send a message in a channel with information about the finished game and the link to download the demo.

**Comment by Max66888** [comment]
I hope he not only supports Discord, but also other channels such as Onedrive or Webdev
The whole Chinese Mainland is unable to visit Discard normally
Thanks！
