### ISSUE TITLE
A full implementation of CSSharp's permission system

### ISSUE THREAD

**Issue by ChocOranger** [shobhit-pathak/MatchZy#33]
Thanks for adding basic CSSharp admin, however, as I said in the original Issue Request you should bite the bullet and add proper granular support for admin commands as supported by CSSharp.
Delaying it and doing the fudge fix you've implemented will cause way more work in the longer term. I'm looking to the future for this plugin and can see where it can go and how it can not only support teams but also community servers (I know that's not currently a focus)

As you'll already know the CSSharp admin permission system does all the work for you. You just need to specify the admin level needed for a command and it will allow or block access as needed. No need for adding extra code inside every admin command you add.

Here's a suggestion for a full and proper fix that's extremely powerful (inspired by @crashzk in the original Issue request).

Each admin command is grouped into the standard levels CSSharp provides.

eg .map and .prac are grouped into @css/changemap so more junior members of a team can practice.
Match commands eg .start and .reloadadmins should be reserved for more senior admins. 

**Each command also has an additional admin setting based on its name.eg @custom/prac**

```
[RequiresPermissionsOr("@css/map", "@custom/prac")]
public void OnPracCommand(CCSPlayerController? player, CommandInfo? command)
```

An admin could now be given access to just the practice command without the ability to change the map (it's an example only - you probably wouldn't do this)

This gives complete control in assigning actions to admins. Users that need basic functionality have it, but also provides extremely powerful control for minimal coding effort. You could even add @custom/generic to each admin command and keep the same admin system you have now where every admin has access to everything (I don't think this is a good idea personally).  @css/generic shouldn't be used as CCSharp should use this as enabling other admin levels.

You will of course need to rip out the current admin checks in commands - looking at the code most are simply removing a couple of lines in about a dozen commands. pause and unpause require the biggest changes.
It's alpha and people should be prepared for changes. 

I'm happy to help in anyway I can. Even if it's just grouping commands.

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for the detailed explanation, helps a lot!
Initially I thought that having the generic permission would be just fine, but it seems that is not the case.

So as you've mentioned, we can do the bifurcation based on roles and commands
But shouldn't there be a super-user kind off permission as well which grands access to all commands (like @css/root or @css/generic)?
```
[RequiresPermissionsOr("@css/generic", "@css/map", "@custom/prac")]
public void OnPracCommand(CCSPlayerController? player, CommandInfo? command)
```

I think this way, a generic admin can access all the commands, or a junior admin with `@css/map` or a player with `@custom/prac` can access this command as well.
We can decide the roles for all of the commands (like starting/restarting the match, admin pause/unpause, restore, etc)

**Comment by crashzk** [comment]
> Hey!
> 
> Thanks for the detailed explanation, helps a lot! Initially I thought that having the generic permission would be just fine, but it seems that is not the case.
> 
> So as you've mentioned, we can do the bifurcation based on roles and commands But shouldn't there be a super-user kind-of permission as well which grants access to all the commands (like @css/root or @css/generic)?
> 
> ```
> [RequiresPermissionsOr("@css/generic", "@css/map", "@custom/prac")]
> public void OnPracCommand(CCSPlayerController? player, CommandInfo? command)
> ```
> 
> I think this way, a generic admin can access all the commands, or a junior admin with `@css/map` or a player with `@custom/prac` can access this command as well. We can decide the roles for all of the commands (like starting/restarting the match, admin pause/unpause, restore, etc)

`@css/root` would be best in this case to have access to everything as mentioned, and if you don't have root access check the other flag.

**Comment by ChocOranger** [comment]
CSSharp has  introduced admin overrides so there is no longer a need to have additional flags based on flags as in my original post.

eg the example I gave would now just be
```
[ConsoleCommand("css_prac", "Starts practice mode")]
[RequiresPermissionsOr("@css/map")]
public void OnPracCommand(CCSPlayerController? player, CommandInfo? command)
```

and for the override giving access to .prac it would be

```
  "Admins_name": {
    "identity": "123456789123456",
    "flags": [ "@css/whatever_flags"
		 ]
   "command_overrides": {
      "css_prac": true
   }
```

This also applies to groups.

As @crashzk stated @css/root grants access to all admin flags.

Incidentally, @css/generic in sourcemod made a player admin but you also had to give them extra permission flags.  eg if you wanted them access to change map they would need both @css/generic and @css/map (using CSSharp terminology). I don't know if this is still the case in CSSharp

**Comment by ChocOranger** [comment]
Here's my suggestion sfor grouping commands into the various admin flags.

**No admin restrictions.** This is as it is currently.
.ready
.unready
.pause
.tech
.unpause
.stay
.switch
.stop
.tac
.coach

.settings This is currently admin protected, but since it just shows the server settings it could be removed from admin 


**Practice commands.** No admin restrictions except for .deletenade

.spawn
.ctspawn
.tspawn
.bot
.nobots
.clear
.fastforward
.god
.savenade
.loadnade
.importnade
.listnades

.deletenade make admin protected with flags @css/config A bit too powerful for regular players I feel.



**Admin flag @css/changemap**

.map
.prac         Having prac here allows players to practice without having full match command access
.exitprac   Isn't prac now togable or there's a pr for it? If so this is no longer required. 


Admin flag @css/config

.knife			
.readyrequired	
.reload_admins	
.restart		
.restore		
.start			
.team1			
.team2			
.whitelist		


The following require implementation of https://github.com/shobhit-pathak/MatchZy/issues/28
Without it you'll end up rewriting the admin work-around for .pause and .unpause. Easier to separate them as part of this. Less code as well.
.forcepause		
.forceunpause	



**Admin flag @css/chat**

.asay


**@css/rcon**

.rcon

**Comment by ChocOranger** [comment]
> Incidentally, @css/generic in sourcemod made a player admin but you also had to give them extra permission flags. eg if you wanted them access to change map they would need both @css/generic and @css/changemap (using CSSharp terminology). I don't know if this is still the case in CSSharp

Tested @css/generic and it isn't required for other admin levels in CSSharp

**Comment by shobhit-pathak** [comment]
Hey guys!

I've updated the admin system as per our discussion here

  - `@css/root`: Grants access to all admin commands
  - `@css/config`: Grants access to config related admin commands
  - `@custom/prac`: Grants access to practice related admin commands
  - `@css/map`: Grants access to change map and toggle practice mode
  - `@css/rcon`: Grants access to trigger RCON commands using `!rcon <command>`
  - `@css/chat`: Grants access to send admin chat messages using `!asay <message>`
  
Do let me know your thoughts here, and whether we are good to close this issue! 

Thanks :D

**Comment by crashzk** [comment]
> Hey guys!
> 
> I've updated the admin system as per our discussion here
> 
> * `@css/root`: Grants access to all admin commands
> * `@css/config`: Grants access to config related admin commands
> * `@custom/prac`: Grants access to practice related admin commands
> * `@css/map`: Grants access to change map and toggle practice mode
> * `@css/rcon`: Grants access to trigger RCON commands using `!rcon <command>`
> * `@css/chat`: Grants access to send admin chat messages using `!asay <message>`
> 
> Do let me know your thoughts here, and whether we are good to close this issue!
> 
> Thanks :D

For me perfect, now it's time to test everything but I believe this is more than perfect. ❤️

**Comment by ChocOranger** [comment]
> Hey guys!
> 
> I've updated the admin system as per our discussion here
> 
> * `@css/root`: Grants access to all admin commands
> * `@css/config`: Grants access to config related admin commands
> * `@custom/prac`: Grants access to practice related admin commands
> * `@css/map`: Grants access to change map and toggle practice mode
> * `@css/rcon`: Grants access to trigger RCON commands using `!rcon <command>`
> * `@css/chat`: Grants access to send admin chat messages using `!asay <message>`
> 
> Do let me know your thoughts here, and whether we are good to close this issue!
> 
> Thanks :D

Great job :)
Everything seems to work. I concentrated my testing on admin overrides and groups.
Overrides work perfectly. 

Admin groups don't work but I think it's an issue with CSSharp not your implementation. I'll do some further testing.

I'm curious though, why did you effectively create your own admin system rather than use the built in CSSharp admin system?
There's less code using the CSSharp's system and all admin flags are linked to the command's definition making it more readable.

Excellent job though. For me this issue can be closed.

**Comment by shobhit-pathak** [comment]
Hey, thanks for the feedback and testing! :D 
When I started working on MatchZy, CSSharp didn't had an admin system, that is why I had to develop my own.

Thanks for the confirmation, I'll close this issue!
