### ISSUE TITLE
[REQ] Do we really need this welcome message?

### ISSUE THREAD

**Issue by crashzk** [shobhit-pathak/MatchZy#35]
https://github.com/shobhit-pathak/MatchZy/blob/53b613e679fbb954daedd74c07eff4a274bc1d4e/MatchZy.cs#L169

I believe we can remove this feature, or improve it if we really need it.

Option to activate this welcome message, so in the future with support for translating messages we can customize it to our liking, etc.

**Comment by shobhit-pathak** [comment]
Hey!

Haha this is actually not needed, when I started with the development on CSSharp, I was trying a few things (playing with chats, events, etc) and that's when I added this message which I later forgot to remove :P 

I'll take care of it in the next update!
Also, what would be the better option? To completely remove it or to improve it? By improving, do we mean to make this message configurable?

**Comment by crashzk** [comment]
I imagined something like that... haha

I believe the best thing would be to remove it. A configurable message would be interesting, but what use is it, just to welcome you and so on. Disclosure that the server uses MatchZy and such...

I believe that we can use methods for this.

**Comment by shobhit-pathak** [comment]
Hey!
This has been removed in the latest release.
Thanks! :D
