### ISSUE TITLE
Demos are not loading

### ISSUE THREAD

**Issue by lukyefps** [shobhit-pathak/MatchZy#36]
Hello. I've been trying this plugin lately on my dedicated server and everything works fine, i start a match by saying .start on all chat and it works perfectly and when the scrim ends i simply change the map because i have no idea how to stop the match(i changed the live.cfg settings for the command "mp_match_can_clinch" from true to false), and once i change the map the demo is stored in the default MatchZy folder but when i try to load the demo it won't load at all, it keeps loading for an eternity. I think the demo gets corrupted for some reason.

**Comment by shobhit-pathak** [comment]
Hey!

I've tried playing many of the demos and all of them were working as expected but I haven't tried it with `mp_match_can_clinch false`
Thanks for pointing out, I'll try to re-create this and deploy a fix ASAP!

**Comment by ar1a** [comment]
you should be able to stop a match, and save the demo with `.restart`

@shobhit-pathak would it be possible to print a chat message when a demo has finished saving?

**Comment by ChocOranger** [comment]
Try setting 'tv_record_immediate 1' then the demo doesn't wait for the cstv delay. This also has the bonus of not requiring a slot for CSTV.

Normally 'tv_delaymapchange 1' forces a delay of map change until the demo records the extra cstv delay. Maybe the instant map change is cutting the demo short and corrupting the demo.
