### ISSUE TITLE
Change flash blind display to 1 or 2 decimal places

### ISSUE THREAD

**Issue by ar1a** [shobhit-pathak/MatchZy#38]
Hi, if possible it would be much nicer to change flash display to be only one or two decimal places. The huge precision is really unnecessary and makes reading the chat logs a bit harder.

**Comment by shobhit-pathak** [comment]
Hey!

I'll take this up in the next update and round if off upto 2 decimal places
Thanks! :D

**Comment by shobhit-pathak** [comment]
Hey!

This has been fixed in the latest release, thanks! :D
