### ISSUE TITLE
Bots are not added to the server

### ISSUE THREAD

**Issue by kifstton** [shobhit-pathak/MatchZy#4]
When entering a command into the chat, the ".bot" writes an error: Cannot add bots, the team is full! Use .nobots to remove the current bots.
Although the server is completely empty.

**Comment by shobhit-pathak** [comment]
Hi!
Make sure you have bots enabled on your server and you do not have `-nobots` launch option, else bots cannot be added.

**Comment by kifstton** [comment]
Do you have information on how to check this setting?

**Comment by shobhit-pathak** [comment]
How are you hosting your servers? If you are using steamcmd or pterodactyl, you can check for the launch options and make sure you don't have `-nobots` there.

If you are using any hosting service like Dathost, there will be an option to disable bots in the settings.
