### ISSUE TITLE
[REQ] Webhook API

### ISSUE THREAD

**Issue by FlowingSPDG** [shobhit-pathak/MatchZy#40]
Hello, thank you so much for developing awesome plugin!
I just looked into CounterStrikeSharp, so I'm sorry if somebody talked about it already.

I was developing multiple get5-integrated webpanel system before, I'd like to help developing webhook and/or webpanel with MatchZy!

Is there any schedule or plan to add this? if you have any specification or plan, I'd like to follow and help developing them accordingly!

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for reaching out!
Yes I do have plan to develop match configuration using JSON/HTTP(s) requests and for that a web panel/webhook would be required from where we can setup matches.
I'll start my development for setting-up matches using JSON/HTTP(s) and I think after that work on web panel can be started! :D

**Comment by FlowingSPDG** [comment]
Hello! thank you for quick response 🔥 
Nice, awesome! So I assume that we're going to use JSON over HTTP(s)?
(main reason I'm asking this is we could not use protocol other than HTTP1.1 because we did not have any helpful extension for sourcepawn, and now we have variety of choices with C# libraries such as Protocol Buffers)

I'd like to corporate developing/planning JSON structure or event formatting if i can!

**Comment by shobhit-pathak** [comment]
Hey!

The idea is to initially have a match setup system similar to Get5 where we can either use a JSON file to configure it, or hit a URL where the JSON file is hosted (`get5_loadmatch_url`)
I think once that is done, we can explore subscribing and pushing events on a webhook and also have a web panel around it (as you've mentioned we have variety of choices with C# libraries)

Also, if you want we can continue this discussion on discord (My ID: wdgodxd, MatchZy discord: https://discord.gg/2zvhy9m7qg)

Thanks!

**Comment by FlowingSPDG** [comment]
Makes sense, yea I'd love to see loadmatch system like that!

Is there any internal match setting class or something? I think I can dig into it if we have something to start with!

**Comment by shobhit-pathak** [comment]
Hey!

Apologies for the late reply

We can now setup matches in MatchZy using `matchzy_loadmatch` and `matchzy_loadmatch_url` (with almost similar schema to Get5)
You can read more about it on: https://shobhit-pathak.github.io/MatchZy/match_setup/
