### ISSUE TITLE
Coach taking up "competitive spawns" on maps where there are only 5 "competitive spawns"

### ISSUE THREAD

**Issue by Aureo3** [shobhit-pathak/MatchZy#42]
Coach is taking up "competitive spawns" on maps where there are only 5 "competitive spawns", pushing players to non-default spawns. A big deal on certain maps where there are instant smokes based off the five spawns (ancient t and ct, anubis ct, vertigo t and ct, inferno ct) pracc and refrag have managed to avoid this issue by somehow spawning the coaches above the players(maybe they just spawn normally and then manually check the positions of the coach/5 players, then teleport?). Love the plugin and all the great work you've been putting in aside from this!

**Comment by shobhit-pathak** [comment]
Hey!

Yes I think we can teleport the player taking the competitive spawn somewhere else and bring back the actual player to the competitive spawn to avoid this issue.
I'll also explore if any better way is available and I'll try to fix this asap

Thanks! :D

**Comment by Aureo3** [comment]
any update on this? I know this, as well as coach having to run out of the way of players is keeping many teams from switching to this over pracc.com/refrag servers.
thanks for your work!

**Comment by shobhit-pathak** [comment]
Hey!

Apologies for the delay, couldn't get the chance to work on it, but I'm trying to resolve it ASAP

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

This has been resolved in the latest releases of MatchZy!

Thanks!
