### ISSUE TITLE
[Issue] Stopping demo recording/match when playout is on

### ISSUE THREAD

**Issue by realm2** [shobhit-pathak/MatchZy#45]
Hello,

Before the most recent update, I used to change map to stop the demo recording. However, now I cant find a way to stop the demo recording as it says "Cannot switch maps when game is active." 

Thanks.

**Comment by shobhit-pathak** [comment]
Hey!

If you want to end the match and stop demo recording, use `.restart` command
It will force-end the match and save the demo. Then you can either change the map or start a new match again!

Thanks!
