### ISSUE TITLE
[Suggestion] Pugsetup like demo name format

### ISSUE THREAD

**Issue by donjo9** [shobhit-pathak/MatchZy#55]
I used to use Pugsetup in CSGO, and liked the way that it enables custom format of the demo name

[Pugsetup](https://github.com/splewis/csgo-pug-setup)

I'm going to add it to my own fork, but if the feature has your interest we could discuss how it should work and I could make a PR

**Comment by shobhit-pathak** [comment]
Hey!

Yes actually I was thinking to make demo name configurable using some format convar
It would be great if you can raise a PR for that :D 

Thanks!

**Comment by donjo9** [comment]
Created a PR #68

**Comment by shobhit-pathak** [comment]
Thanks for the PR and contribution!
This has been included in 0.6.1-alpha release!
