### ISSUE TITLE
[BUG] Problems with the pause feature

### ISSUE THREAD

**Issue by borzaka** [shobhit-pathak/MatchZy#57]
The tactical, technical and admin pauses can conflict with each other.

Scenarios and bugs:
- During a regular `.pause`, a player can still type `.tac`, to start a tactical timeout. That will override the regular pause and start a tactical one. And after about 30 seconds, the game resumes.
- Players can even unpause a forced pause by typing `.tac`.  That will override the admin pause and start a tactical one. And after about 30 seconds, the game resumes.
- Payers can type `.pause` during a `.tac` pause, but it won't stop the tactical timeout.

In every scenario above, the plugin still thinks the game is paused, even after the tactical timeout finished and the game resumes. So you can't call another pause, unless booth team types `.unpause`, which is very confusing. And the chat keeps spamming the `.unpause`.

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for the detailed explanation :D 
For tactical timeout, we use game commands `timeout_terrorist_start` and `timeout_ct_start` and it seems they internally call mp_pause/unpause_match which is causing the conflict between `.pause` and `.tac`

I'll add some additional checks in the next update so avoid these conflicts! 

Thanks!

**Comment by borzaka** [comment]
Thanks in advance!

The native way to call a tactical timeout is to call a vote from the game's menu. This vote will fail if another pause is happening.

**Comment by shobhit-pathak** [comment]
Hey!

All of the above issues have been resolved in the v0.5.1-alpha release of MatchZy (https://github.com/shobhit-pathak/MatchZy/releases/)

Thanks!
