### ISSUE TITLE
[Bug] spawn + bot commands not working

### ISSUE THREAD

**Issue by kevkaprojects** [shobhit-pathak/MatchZy#62]
Hello,

the day before yesterday I was practicing instant smokes on Ancient, where the .spawn command and its derivatives (.tspawn / .ctspawn) come in handy.
Today, I noticed this feature does not seem to work anymore. Also .bot commands (e.g. .bot, .crouchbot, .boost) do not work properly anymore, as the bot gets added, but does maintain its spawn point. For .crouchbot, it does crouch on spawn, but does not change position.

I have tested a fresh install with the newest current version of 0.5.1-alpha with the included CSSharp.
Additionally, I have tested with an old metamod version (2.0.0+1225) and the latest (2.0.0+1275).

I do believe this is a bug, but the possibility that this is a problem on my end exists.
If you cannot reproduce this issue, I would be happy to receive some tips :)
Thanks in advance!

For debug purposes I have included a snippet of the chat log on my server:

[MatchZy] [EventPlayerChat] UserId(Index): 1 playerUserId: 0 Message: .spawn 1
[All Chat][kevka^ (172587987)]: .spawn 1
[MatchZy] [EventPlayerChat] UserId(Index): 1 playerUserId: 0 Message: .spawn 2
[All Chat][kevka^ (172587987)]: .spawn 2
[MatchZy] [EventPlayerChat] UserId(Index): 1 playerUserId: 0 Message: .bot
[All Chat][kevka^ (172587987)]: .bot
ClientPutInServer create new player controller [Lieutenant]
"Lieutenant<4><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 3 willSwitch 0, 518.77 
[MatchZy] [TemporarilyDisableCollisions] Disabling kevka^ Lieutenant
[MatchZy] [EventPlayerChat] UserId(Index): 1 playerUserId: 0 Message: .crouchbot
[All Chat][kevka^ (172587987)]: .crouchbot
ClientPutInServer create new player controller [Goggles]
"Goggles<5><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 3 willSwitch 0, 613.27 
[MatchZy] [TemporarilyDisableCollisions] Disabling kevka^ Goggles

**Comment by shobhit-pathak** [comment]
Hey!

Today's CS2 game update has broken teleport feature of practice mode.

To fix it, you will have to update CSSharp, or download matchzy-with-cssharp release from here (I've updated the release):
https://github.com/shobhit-pathak/MatchZy/releases/tag/0.5.1-alpha

Or simply update `addons/counterstrikesharp/gamedata/gamedata.json` file with this:
https://raw.githubusercontent.com/roflmuffin/CounterStrikeSharp/74fd0e0832dbd8a8a2385bc76f0c5f585196b452/configs/addons/counterstrikesharp/gamedata/gamedata.json

Thanks!

**Comment by kevkaprojects** [comment]
I have replace the gamedata.json like you suggested and it restored functionality to the teleport feature.

Thanks for your help :D
