### ISSUE TITLE
[INFO] simple question

### ISSUE THREAD

**Issue by inFqm** [shobhit-pathak/MatchZy#63]
I run just one plugin on CounterStrikeSharp to have a ranking system when server is set on FFA. Does MatchZy disable all plugins when PUG mod is launched?

**Comment by shobhit-pathak** [comment]
Hey!

MatchZy doesn't disable any other plugin hence you can use other plugins as well with MatchZy.

If you want to disable any CSSharp plugin, you can use `css_plugins stop "<plugin_name>"` command to disable it, and `css_plugins start "<plugin_name"> to start it again. You can put these commands in your CFG file to automatically enable/disable plugin whenever needed

**Comment by inFqm** [comment]
Thanks a lot for the tip! Can I put the disable command into the comp.cfg and the enable one in the casual?

**Comment by shobhit-pathak** [comment]
Hey!

Yes, you will have to put the disable command in the cfg which you are sure is going to execute when you change the plugin. For example, you can put it in warmup.cfg of MatchZy if you want to disable any other plugin when MatchZy starts

Similarly, you can put the start command in casual cfg if that is going to execute once you want to turn the plugin on
