### ISSUE TITLE
.spawn number doesn't work 

### ISSUE THREAD

**Issue by mrv0jta91** [shobhit-pathak/MatchZy#64]
what title says.. it game it says "moved to spawn x/x" but doesn't port you there
Edit 1: .bot doesn't work for me as well - just spawns bot to spawn, not my position.

**Comment by shobhit-pathak** [comment]
Hey!

Recent CS2 game update has broken teleport and bot spawn feature of practice mode.

To fix it, you will have to update CSSharp, or download matchzy-with-cssharp release from here (I've updated the release):
https://github.com/shobhit-pathak/MatchZy/releases/latest

Or simply update addons/counterstrikesharp/gamedata/gamedata.json file with this:
https://raw.githubusercontent.com/roflmuffin/CounterStrikeSharp/74fd0e0832dbd8a8a2385bc76f0c5f585196b452/configs/addons/counterstrikesharp/gamedata/gamedata.json

Thanks!

**Comment by mrv0jta91** [comment]
> Hey!
> 
> Recent CS2 game update has broken teleport and bot spawn feature of practice mode.
> 
> To fix it, you will have to update CSSharp, or download matchzy-with-cssharp release from here (I've updated the release): https://github.com/shobhit-pathak/MatchZy/releases/latest
> 
> Or simply update addons/counterstrikesharp/gamedata/gamedata.json file with this: https://raw.githubusercontent.com/roflmuffin/CounterStrikeSharp/74fd0e0832dbd8a8a2385bc76f0c5f585196b452/configs/addons/counterstrikesharp/gamedata/gamedata.json
> 
> Thanks!

worked! thanks mate. One more question? Is that the same gamedata.json file as it was before the update? So I know what to replace if the same issue reocures again.

**Comment by shobhit-pathak** [comment]
Hey!

The `gamedata.json` files need to be changed only if signatures of any function is changed in an update.
This doesn't happen usually in most of the updates but signatures can change in a major update.
In that case, you can get the updated `gamedata.json` from CSSharp's repository or you can join MatchZy's discord and get the update from there.

Thanks!
