### ISSUE TITLE
mathzy

### ISSUE THREAD

**Issue by Matthews02** [shobhit-pathak/MatchZy#71]
how to get admin rights
I have it like this and it doesn't work

{
  "Erikj": {
    "identity": "76561198299893462",
    "immunity": 100,
    "flags": [
      "@css/root",
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": false
    }
  },
  "Another erikj": {
    "identity": "STEAM_0:1:1",
    "flags": ["@mycustomplugin/admin"]
  }
}

**Comment by shobhit-pathak** [comment]
Hey!

You can read the guide to create admins here:
https://shobhit-pathak.github.io/MatchZy/configuration/#creating-admins

Make sure that you are entering the correct steam id and the JSON structure is correct
Also, reload admins after adding them in the file, or restart the server.

Thanks!

**Comment by Matthews02** [comment]
I already have the rights, but I don't know when I write .asay I write as admin

but I can't always run live as an administrator and when I enter !css admin it says that I don't have access to the right, how can I start to have an admin table

**Comment by Matthews02** [comment]
now i have {
"WD-": {
    "identity": "76561198299893462",
    "flags": [
    "@css/root"
    ]
},
"Another admin": {
    "identity": "STEAM_1:0:169813867",
    "flags": [
    "@css/config",
    "@css/rcon"
    ]
}
}

**Comment by shobhit-pathak** [comment]
Hey

If .asay if working for you, it means that you have the admin power
Make sure that you have "@css/root" in your flags to get access to all the admin commands of MatchZy

And I would suggest you to join the discord (https://discord.gg/2zvhy9m7qg) so that you can get faster help there.

Thanks!

**Comment by Matthews02** [comment]
just tell me where to add it to the file so that the admin table with rights goes to me
I have it too sharp
where to write it down

**Comment by Matthews02** [comment]
now i have {
"Matthews": {
    "identity": "76561198299893462",
    "flags": [
    "@css/root"
    ]
},
"Another admin": {
    "identity": "SteamID 2",
    "flags": [
    "@css/config",
    "@css/rcon"
    ]
},
"Vitulas": {
    "identity": "76561198354467190",
    "flags": [
    "@css/root"
    ]
}
}
