### ISSUE TITLE
Fatal bug

### ISSUE THREAD

**Issue by Scentedsoap1314** [shobhit-pathak/MatchZy#72]
The game will not reset after the end in on the settlement page
The waiting time on the settlement page is too long， cfg file no code  can modify this time
Replacing the map，plugin to not work

**Comment by shobhit-pathak** [comment]
Hey!

The game resets once `mp_match_restart_delay` is over. This may also get modified as per the GOTV Delay to wait for the GOTV Broadcast to end.

Could you please elaborate what is the exact issue you are facing in your case?

Thanks!

**Comment by Scentedsoap1314** [comment]
The settlement page have a waiting time of two minutes，but it will not reset when the time is up，will get stuck settlement page，hereand new players entering the server will get stuck in place

**Comment by Scentedsoap1314** [comment]
In server backend replacing the map,will cause the plugin to not work

**Comment by shobhit-pathak** [comment]
Hey!

Would it be possible for you to record a video for the same?
I'm not able to reproduce it on my end

Thanks!

**Comment by Scentedsoap1314** [comment]
I returned version 0.5.1，because this version is quite perfect
