### ISSUE TITLE
Players entering and exiting automatically generate robots

### ISSUE THREAD

**Issue by 925916995** [shobhit-pathak/MatchZy#73]
Players entering and exiting automatically generate robots。Is there any solution? Still waiting for the problem to be fixed。
Every time a player enters, if they are ready or not, and then exits the server, there will be a bot left on their side that can be killed, but the tab panel cannot see this person。

**Comment by shobhit-pathak** [comment]
Hey!

This is not a bug from plugin side, but it is a bug from CS2 itself.
So we will have to wait for valve to fix it :D 

Thanks!
