### ISSUE TITLE
[Suggestion] Removing smoke thrown by user with new cs2 command

### ISSUE THREAD

**Issue by tama2cs** [shobhit-pathak/MatchZy#78]
Hey! 

In cs2 there is a new command that can remove smoke grenades and their smoke. This is very useful when practicing nades and not having to wait for the smoke to dissapate. (In csgo people made a fast-forward command to skip time to achieve this -> .ff)

Right now the command doesn't seem to work on servers, but if you run your own practice match you can use it. 

ent_fire smokegrenade_projectile kill; stopsound

I think this would be a great addition to the practice mode.
Something like ".kill_smoke" and ".ks" for faster use. Making it work with a say bind so you can bind "bind n say .ks" would be amazing.

Also, thank you for everything you've done so far already!

**Comment by shobhit-pathak** [comment]
Hey!

Command for killing smokes, molly, etc is already there!
You can use `.clear` for that, and you can bind it using `bind n css_clear`

Thanks!

**Comment by tama2cs** [comment]
oops 😳
