### ISSUE TITLE
Grenate Flytime

### ISSUE THREAD

**Issue by CloudEMPG** [shobhit-pathak/MatchZy#79]
Hey!
It would be a very nice addition if you could add a grenade flytime feature.

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for the suggestion, I'll surely try to add this in the next update! :D

**Comment by shobhit-pathak** [comment]
Hey!

This has been added in 0.7.0 release of MatchZy (https://github.com/shobhit-pathak/MatchZy/releases/tag/0.7.0)

Thanks!
