### ISSUE TITLE
Can I fork out a Chinese version of your warehouse? I originally planned to use it myself, but I want to keep it on Github  https://github.com/Max66888/MatchZy-Chinese

### ISSUE THREAD

**Issue by Max66888** [shobhit-pathak/MatchZy#8]
Can I fork out a Chinese version of your warehouse? I originally planned to use it myself, but I want to keep it on Github

https://github.com/Max66888/MatchZy-Chinese

**Comment by mrc4tt** [comment]
Yeah you can do that.
You dont need to ask, anyone can fork.

Go for it.

**Comment by shobhit-pathak** [comment]
Sure, you can do that!
