### ISSUE TITLE
Missing data in Get5

### ISSUE THREAD

**Issue by victorpahuus** [shobhit-pathak/MatchZy#80]
I'm not quite sure where the problem occurs, but I find that Get5 can control the server via RCON just fine. But when a match is over, the data is not updated in Get5, in fact, no data about the match comes in.

Since all documentation about Get5 is about Sourcemod, I don't even know if I need to install anything. All matches run fine and can be started without any problems. The only thing that indicates errors is the below from the log.

> [MatchZy] [ExecuteChangedConvars] Execing: get5_web_api_url "https://get5.domain.dk/api"
> [MatchZy] [ExecuteChangedConvars] Execing: get5_check_auths "1"
> Unknown command 'get5_web_api_url'!
> Unknown command 'get5_check_auths'!

I hope you can help!

**Comment by shobhit-pathak** [comment]
Hey!
According to the logs, `get5_web_api_url` command is being sent to the server, but it should be sending `get5_remote_log_url`
This means either you're using an older version of G5API, or it is not able to detect the server properly
So you can follow these 2 steps:
1. Remove and re-add server in you Get5 Panel
2. If the above step doesn't work, re-install the latest version of G5V and G5API (MatchZy works with the latest one only).
If you need help installing the latest version, you can install it using docker following the steps mentioned here:
https://shobhit-pathak.github.io/MatchZy/get5/#using-docker

Thanks!

**Comment by victorpahuus** [comment]
I followed your instructions and it didn't work, even after reinstalling servers and get5. But out of the blue, it suddenly worked. Thanks for a great project!
