### ISSUE TITLE
Plugins not running

### ISSUE THREAD

**Issue by BigSaVo** [shobhit-pathak/MatchZy#88]
Today there was a server update of Cs2. Unfortunately the plugin apparently no longer works. Does anyone have an idea how I can get the plugin to work again? I have Metamod mmsource-2.0.0-git1280-linux and counterstrikesharp-build-161-linux-b9ca63a.

Despite the current versions, the commands in the chat do not work.

Can anyone help me?

**Comment by shobhit-pathak** [comment]
Hey!

Yes today's update has broken the plugins, we will have to wait for an update of CSSharp, and that should fix everything!
I'll inform about the update in the discord once that is released

Thanks!

**Comment by koikinov** [comment]
Hey,

It would be nice if you add also on practice mode that timer how long grenades fly until they hit ground.
It helps a lot finding timing grenade setups, thanks.

**Comment by shobhit-pathak** [comment]
Hey @BigSaVo, the plugin should be working fine now with latest metamod + cs# + matchzy
@koikinov Grenade flytimes have also been added in 0.7.0 release of MatchZy (https://github.com/shobhit-pathak/MatchZy/releases/tag/0.7.0)

Thanks!
