### ISSUE TITLE
(.map) command causes segmentation fault

### ISSUE THREAD

**Issue by JustinSafrix** [shobhit-pathak/MatchZy#89]
![Screenshot 2024-02-08 173747](https://github.com/shobhit-pathak/MatchZy/assets/40339373/29eef230-f14a-4705-abe2-b0be9cd604dc)

Not sure exactly why this could be, but when using the .map command e.g. (.map de_anubis) the map starts to change but then the server crashes.

**Comment by shobhit-pathak** [comment]
Hey!

Yeah I've also seen this multiple times, but I think this is an issue with the game itself (when bots are added into the server), because we simply call `changelevel` command behind the scenes.
Though I'll re-check what could be causing this crash.

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

We've made some improvements, you can try using `.map` command now. Also the crash can be because of bots/GOTV which is a known CS2 issue, hence closing this.
