### ISSUE TITLE
[BUG] !stay or !switch not working maybe Event not triggered

### ISSUE THREAD

**Issue by Sh1su** [shobhit-pathak/MatchZy#90]
Hello shobhit,

First of all, the initial situation:
Our main team wanted to play a pracc game today.
Unfortunately it was not possible to start the match with !stay or !switch after the knife round.

After a little research in the source code, I discovered that the EventCsWinPanelRound event is no longer triggered. 

```c
RegisterEventHandler<EventCsWinPanelRound>((@event, info) => {
    Log($"[EventCsWinPanelRound PRE] finalEvent: {@event.FinalEvent}");
    if (isKnifeRound && matchStarted) {
        HandleKnifeWinner(@event);
    }
    return HookResult.Continue;
}, HookMode.Pre);
```

This means that the HandleKnifeWinner function is not executed.

This in turn means that the KnifeWinner variable is not overwritten with 2 or 3. 

As a result, the OnTeamStay or OnTeamSwitch function does not know who has now won. 

I also don't quite understand when the EventCsWinPanelRound event is triggered. Can you clarify this for me?

Could it have something to do with the last update?
___
### Meta Info
    Metamod:Source version 2.0.0-dev+1282
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Feb  7 2024 19:09:08
    Built from: https://github.com/alliedmodders/metamod-source/commit/3740821
    Build ID: 1282:3740821
    http://www.metamodsource.net/

### meta list
  ```shell
  Listing 1 plugin:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
```
### css_plugins list
  ```shell
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADED]: "MatchZy" (0.5.1-alpha) by WD- (https://github.com/shobhit-pathak/)
    A plugin for running and managing CS2 practice/pugs/scrims/matches!
```
___
### Server Console Output
  ```shell
[MatchZy] [EventPlayerChat] UserId(Index): 3 playerUserId: 2 Message: .stay
[MatchZy] [!stay command] 2, TeamNum: 2, knifeWinner: 0, isSideSelectionPhase: True
[All Chat][Sh1su (413884184)]: .stay
[MatchZy] [EventPlayerChat] UserId(Index): 3 playerUserId: 2 Message: .switch
[MatchZy] [!switch command] 2, TeamNum: 2, knifeWinner: 0, isSideSelectionPhase: True
[All Chat][Sh1su (413884184)]: .switch
```

**Comment by shobhit-pathak** [comment]
Hey!

After the recent CS2 update, `EventCsWinPanelRound` has stopped triggering (which earlier used to trigger when a team wins the round), which means we will now have to handle knife winner in `EventRoundEnd`. I've been working on its fix, and I'll release the update in a day or two.

Till then, you can disable the knife round using `.rk` in chat, or `matchzy_knife_enabled_default false`

Thanks!

**Comment by Sh1su** [comment]
Hey! 

Thanks for the fast answer.

**Comment by Cherno-Beliy** [comment]
Is there any way to fix this during the match?
