### ISSUE TITLE
.pause DOES not work

### ISSUE THREAD

**Issue by jrlbss77** [shobhit-pathak/MatchZy#91]
When you call for a .pause. Like a TECH it calls a 0.45s pause.

**Comment by shobhit-pathak** [comment]
Hey!

`.pause` can be used for tactical timeout, as well technical timeout.
You can set `matchzy_use_pause_command_for_tactical_pause false` to use `.pause` as tech pause.
For tactical pause, the time and number of pauses depends on `mp_team_timeout_max` and `mp_team_timeout_time` which you can change from `live.cfg`

Thanks!
